Add coverage to test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,8 +29,23 @@ jobs:
           echo "NEXT_PUBLIC_SITE_URL=${{ env.NEXT_PUBLIC_SITE_URL }}" >> $GITHUB_ENV
           echo "NAME_DEVELOP=${{ env.NAME_DEVELOP }}" >> $GITHUB_ENV
 
-      - name: Run tests 🧪
-        run: npm test
+      - name: Run Jest tests with coverage 🧪
+        run: npm test -- --coverage
+
+      - name: Upload Jest coverage report 📊
+        uses: actions/upload-artifact@v4
+        with:
+          name: jest-coverage
+          path: coverage        
+
+      - name: Validate coverage
+        run: |
+          COVERAGE=$(node -e "console.log(require('./coverage/coverage-summary.json').total.lines.pct)")
+          echo "Total coverage: $COVERAGE%"
+          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
+            echo "Coverage is too low! Failing the pipeline."
+            exit 1
+          fi
 
       - name: Build project 🔥
         run: npm run build
